from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
options = Options()
options.add_experimental_option("detach", True)
driver = webdriver.Chrome(options=options)
driver.get('https://uat.magnusonhotels.com/')
driver.maximize_window()
# Click on the login button
driver.find_element(By.CLASS_NAME, "loginbtn").click()
# driver.find_element(By.CLASS_NAME, "signup").click()
time.sleep(5)
driver.find_element(By.ID,'login_btn').click()
driver.find_element(By.XPATH, "/html/body/section[6]/div/div[1]/div[2]/form/div[5]/div/div/div/p/a").click()
first_name = driver.find_element(By.NAME,"reg_fname")
first_name.send_keys("rohit")
last_name = driver.find_element(By.NAME,"reg_lname")
last_name.send_keys("xyz")
enter_mail = driver.find_element(By.NAME,"reg_email")
enter_mail.send_keys("login04@yopmail.com")
select_affiliation = driver.find_element(By.XPATH,'//*[@id="reg_affiliation"]')
select_affiliation.send_keys("Student")
enter_apt = driver.find_element(By.XPATH,'//*[@id="address_2"]')
enter_apt.send_keys("MU-11")
select_country = driver.find_element(By.XPATH,'//*[@id="reg_country"]')
select_country.send_keys("United Kingdom")
state = driver.find_element(By.NAME,"reg_state")
state.send_keys("Null")
enter_city = driver.find_element(By.NAME,"reg_city")
enter_city.send_keys("London")
enter_postal = driver.find_element(By.NAME,"reg_postcode")
enter_postal.send_keys("N11 B22")
enter_password = driver.find_element(By.NAME,"reg_password")
enter_password.send_keys("Test@123")
enter_confirm = driver.find_element(By.NAME,"reg_confirmpassword")
enter_confirm.send_keys("Test@123")
driver.find_element(By.XPATH, '//*[@id="mgh__signup"]/div[7]/div/div/label/span').click()
driver.find_element(By.XPATH, '//*[@id="mgh__signup"]/div[8]/div/div/label/span').click()
driver.find_element(By.CSS_SELECTOR,"input[value = 'SIGN UP'").click()